# Generated by Django 5.1.6 on 2025-02-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
